# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Sample-SwiftLintAndDanger' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample-SwiftLintAndDanger

  pod 'SwiftLint'

  target 'Sample-SwiftLintAndDangerTests' do
    inherit! :search_paths
    
    pod 'SwiftLocalhost'
    
    # Pods for testing
  end

end
